/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import { HttpHeaders, httpResource } from '@angular/common/http';
import type {
  HttpContext,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest,
} from '@angular/common/http';

import type { ResourceStatus, Signal } from '@angular/core';

import type {
  LocationAreaDetail,
  LocationAreaListParams,
  LocationDetail,
  LocationListParams,
  PaginatedLocationAreaSummaryList,
  PaginatedLocationSummaryList,
  PaginatedPalParkAreaSummaryList,
  PaginatedRegionSummaryList,
  PalParkAreaDetail,
  PalParkAreaListParams,
  RegionDetail,
  RegionListParams,
} from '@poke/poke-api/model';

export interface OrvalHttpResourceRequestExtension {
  /** Extra headers merged over generated headers. Pass a function to read signals reactively. */
  headers?: HttpResourceRequest['headers'] | (() => HttpResourceRequest['headers']);
  /** Angular HttpContext forwarded to the underlying request. Pass a function to derive it reactively. */
  context?: HttpContext | (() => HttpContext);
  /** Last-resort escape hatch: transform the final request descriptor. Runs inside the resource's reactive context. */
  request?: (request: HttpResourceRequest) => HttpResourceRequest;
}

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = (TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>) &
  OrvalHttpResourceRequestExtension;

function mergeOrvalResourceHeaders(
  base: HttpResourceRequest['headers'],
  extra: HttpResourceRequest['headers'],
): HttpResourceRequest['headers'] {
  if (!base) return extra;
  if (!extra) return base;
  if (base instanceof HttpHeaders || extra instanceof HttpHeaders) {
    const toHeaderValue = (value: string | readonly string[]): string | string[] =>
      Array.isArray(value) ? Array.from(value, String) : String(value);
    let merged =
      base instanceof HttpHeaders
        ? base
        : Object.entries(base).reduce(
            (headers, [key, value]) => headers.set(key, toHeaderValue(value)),
            new HttpHeaders(),
          );
    const extraRecord =
      extra instanceof HttpHeaders
        ? extra.keys().reduce<Record<string, string[]>>((record, key) => {
            const values = extra.getAll(key);
            if (values) record[key] = values;
            return record;
          }, {})
        : extra;
    for (const [key, value] of Object.entries(extraRecord)) {
      merged = merged.set(key, toHeaderValue(value));
    }
    return merged;
  }
  return { ...base, ...extra };
}

export function applyOrvalRequestExtension(
  request: string | HttpResourceRequest,
  options?: OrvalHttpResourceRequestExtension,
): HttpResourceRequest {
  const base: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
  if (
    !options ||
    (options.headers === undefined &&
      options.context === undefined &&
      options.request === undefined)
  ) {
    return base;
  }
  let next: HttpResourceRequest = { ...base };
  const extraHeaders = typeof options.headers === 'function' ? options.headers() : options.headers;
  if (extraHeaders !== undefined) {
    next = { ...next, headers: mergeOrvalResourceHeaders(next.headers, extraHeaders) };
  }
  const context = typeof options.context === 'function' ? options.context() : options.context;
  if (context !== undefined) {
    next = { ...next, context };
  }
  return options.request ? options.request(next) : next;
}

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function locationListResource(
  params: Signal<LocationListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedLocationSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedLocationSummaryList>;
  },
): HttpResourceRef<PaginatedLocationSummaryList>;
export function locationListResource(
  params?: Signal<LocationListParams>,
  options?: OrvalHttpResourceOptions<PaginatedLocationSummaryList, unknown>,
): HttpResourceRef<PaginatedLocationSummaryList | undefined>;
export function locationListResource(
  params?: Signal<LocationListParams>,
  options?: OrvalHttpResourceOptions<PaginatedLocationSummaryList, unknown>,
): HttpResourceRef<PaginatedLocationSummaryList | undefined> {
  return httpResource<PaginatedLocationSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/location/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function locationRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<LocationDetail, unknown> & {
    defaultValue: NoInfer<LocationDetail>;
  },
): HttpResourceRef<LocationDetail>;
export function locationRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<LocationDetail, unknown>,
): HttpResourceRef<LocationDetail | undefined>;
export function locationRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<LocationDetail, unknown>,
): HttpResourceRef<LocationDetail | undefined> {
  return httpResource<LocationDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/location/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function locationAreaListResource(
  params: Signal<LocationAreaListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedLocationAreaSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedLocationAreaSummaryList>;
  },
): HttpResourceRef<PaginatedLocationAreaSummaryList>;
export function locationAreaListResource(
  params?: Signal<LocationAreaListParams>,
  options?: OrvalHttpResourceOptions<PaginatedLocationAreaSummaryList, unknown>,
): HttpResourceRef<PaginatedLocationAreaSummaryList | undefined>;
export function locationAreaListResource(
  params?: Signal<LocationAreaListParams>,
  options?: OrvalHttpResourceOptions<PaginatedLocationAreaSummaryList, unknown>,
): HttpResourceRef<PaginatedLocationAreaSummaryList | undefined> {
  return httpResource<PaginatedLocationAreaSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/location-area/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function locationAreaRetrieveResource(
  id: Signal<number>,
  options: OrvalHttpResourceOptions<LocationAreaDetail, unknown> & {
    defaultValue: NoInfer<LocationAreaDetail>;
  },
): HttpResourceRef<LocationAreaDetail>;
export function locationAreaRetrieveResource(
  id: Signal<number>,
  options?: OrvalHttpResourceOptions<LocationAreaDetail, unknown>,
): HttpResourceRef<LocationAreaDetail | undefined>;
export function locationAreaRetrieveResource(
  id: Signal<number>,
  options?: OrvalHttpResourceOptions<LocationAreaDetail, unknown>,
): HttpResourceRef<LocationAreaDetail | undefined> {
  return httpResource<LocationAreaDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/location-area/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function palParkAreaListResource(
  params: Signal<PalParkAreaListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPalParkAreaSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPalParkAreaSummaryList>;
  },
): HttpResourceRef<PaginatedPalParkAreaSummaryList>;
export function palParkAreaListResource(
  params?: Signal<PalParkAreaListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPalParkAreaSummaryList, unknown>,
): HttpResourceRef<PaginatedPalParkAreaSummaryList | undefined>;
export function palParkAreaListResource(
  params?: Signal<PalParkAreaListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPalParkAreaSummaryList, unknown>,
): HttpResourceRef<PaginatedPalParkAreaSummaryList | undefined> {
  return httpResource<PaginatedPalParkAreaSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pal-park-area/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function palParkAreaRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PalParkAreaDetail, unknown> & {
    defaultValue: NoInfer<PalParkAreaDetail>;
  },
): HttpResourceRef<PalParkAreaDetail>;
export function palParkAreaRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PalParkAreaDetail, unknown>,
): HttpResourceRef<PalParkAreaDetail | undefined>;
export function palParkAreaRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PalParkAreaDetail, unknown>,
): HttpResourceRef<PalParkAreaDetail | undefined> {
  return httpResource<PalParkAreaDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pal-park-area/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function regionListResource(
  params: Signal<RegionListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedRegionSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedRegionSummaryList>;
  },
): HttpResourceRef<PaginatedRegionSummaryList>;
export function regionListResource(
  params?: Signal<RegionListParams>,
  options?: OrvalHttpResourceOptions<PaginatedRegionSummaryList, unknown>,
): HttpResourceRef<PaginatedRegionSummaryList | undefined>;
export function regionListResource(
  params?: Signal<RegionListParams>,
  options?: OrvalHttpResourceOptions<PaginatedRegionSummaryList, unknown>,
): HttpResourceRef<PaginatedRegionSummaryList | undefined> {
  return httpResource<PaginatedRegionSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/region/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function regionRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<RegionDetail, unknown> & {
    defaultValue: NoInfer<RegionDetail>;
  },
): HttpResourceRef<RegionDetail>;
export function regionRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<RegionDetail, unknown>,
): HttpResourceRef<RegionDetail | undefined>;
export function regionRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<RegionDetail, unknown>,
): HttpResourceRef<RegionDetail | undefined> {
  return httpResource<RegionDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/region/${id()}/`, options),
    options,
  );
}

export type LocationListResourceResult = NonNullable<PaginatedLocationSummaryList>;
export type LocationRetrieveResourceResult = NonNullable<LocationDetail>;
export type LocationAreaListResourceResult = NonNullable<PaginatedLocationAreaSummaryList>;
export type LocationAreaRetrieveResourceResult = NonNullable<LocationAreaDetail>;
export type PalParkAreaListResourceResult = NonNullable<PaginatedPalParkAreaSummaryList>;
export type PalParkAreaRetrieveResourceResult = NonNullable<PalParkAreaDetail>;
export type RegionListResourceResult = NonNullable<PaginatedRegionSummaryList>;
export type RegionRetrieveResourceResult = NonNullable<RegionDetail>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
