/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import { HttpHeaders, httpResource } from '@angular/common/http';
import type {
  HttpContext,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest,
} from '@angular/common/http';

import type { ResourceStatus, Signal } from '@angular/core';

import type {
  BerryDetail,
  BerryFirmnessDetail,
  BerryFirmnessListParams,
  BerryFlavorDetail,
  BerryFlavorListParams,
  BerryListParams,
  PaginatedBerryFirmnessSummaryList,
  PaginatedBerryFlavorSummaryList,
  PaginatedBerrySummaryList,
} from '@poke/poke-api/model';

export interface OrvalHttpResourceRequestExtension {
  /** Extra headers merged over generated headers. Pass a function to read signals reactively. */
  headers?: HttpResourceRequest['headers'] | (() => HttpResourceRequest['headers']);
  /** Angular HttpContext forwarded to the underlying request. Pass a function to derive it reactively. */
  context?: HttpContext | (() => HttpContext);
  /** Last-resort escape hatch: transform the final request descriptor. Runs inside the resource's reactive context. */
  request?: (request: HttpResourceRequest) => HttpResourceRequest;
}

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = (TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>) &
  OrvalHttpResourceRequestExtension;

function mergeOrvalResourceHeaders(
  base: HttpResourceRequest['headers'],
  extra: HttpResourceRequest['headers'],
): HttpResourceRequest['headers'] {
  if (!base) return extra;
  if (!extra) return base;
  if (base instanceof HttpHeaders || extra instanceof HttpHeaders) {
    const toHeaderValue = (value: string | readonly string[]): string | string[] =>
      Array.isArray(value) ? Array.from(value, String) : String(value);
    let merged =
      base instanceof HttpHeaders
        ? base
        : Object.entries(base).reduce(
            (headers, [key, value]) => headers.set(key, toHeaderValue(value)),
            new HttpHeaders(),
          );
    const extraRecord =
      extra instanceof HttpHeaders
        ? extra.keys().reduce<Record<string, string[]>>((record, key) => {
            const values = extra.getAll(key);
            if (values) record[key] = values;
            return record;
          }, {})
        : extra;
    for (const [key, value] of Object.entries(extraRecord)) {
      merged = merged.set(key, toHeaderValue(value));
    }
    return merged;
  }
  return { ...base, ...extra };
}

export function applyOrvalRequestExtension(
  request: string | HttpResourceRequest,
  options?: OrvalHttpResourceRequestExtension,
): HttpResourceRequest {
  const base: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
  if (
    !options ||
    (options.headers === undefined &&
      options.context === undefined &&
      options.request === undefined)
  ) {
    return base;
  }
  let next: HttpResourceRequest = { ...base };
  const extraHeaders = typeof options.headers === 'function' ? options.headers() : options.headers;
  if (extraHeaders !== undefined) {
    next = { ...next, headers: mergeOrvalResourceHeaders(next.headers, extraHeaders) };
  }
  const context = typeof options.context === 'function' ? options.context() : options.context;
  if (context !== undefined) {
    next = { ...next, context };
  }
  return options.request ? options.request(next) : next;
}

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function berryListResource(
  params: Signal<BerryListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedBerrySummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedBerrySummaryList>;
  },
): HttpResourceRef<PaginatedBerrySummaryList>;
export function berryListResource(
  params?: Signal<BerryListParams>,
  options?: OrvalHttpResourceOptions<PaginatedBerrySummaryList, unknown>,
): HttpResourceRef<PaginatedBerrySummaryList | undefined>;
export function berryListResource(
  params?: Signal<BerryListParams>,
  options?: OrvalHttpResourceOptions<PaginatedBerrySummaryList, unknown>,
): HttpResourceRef<PaginatedBerrySummaryList | undefined> {
  return httpResource<PaginatedBerrySummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/berry/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function berryRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<BerryDetail, unknown> & { defaultValue: NoInfer<BerryDetail> },
): HttpResourceRef<BerryDetail>;
export function berryRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<BerryDetail, unknown>,
): HttpResourceRef<BerryDetail | undefined>;
export function berryRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<BerryDetail, unknown>,
): HttpResourceRef<BerryDetail | undefined> {
  return httpResource<BerryDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/berry/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function berryFirmnessListResource(
  params: Signal<BerryFirmnessListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedBerryFirmnessSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedBerryFirmnessSummaryList>;
  },
): HttpResourceRef<PaginatedBerryFirmnessSummaryList>;
export function berryFirmnessListResource(
  params?: Signal<BerryFirmnessListParams>,
  options?: OrvalHttpResourceOptions<PaginatedBerryFirmnessSummaryList, unknown>,
): HttpResourceRef<PaginatedBerryFirmnessSummaryList | undefined>;
export function berryFirmnessListResource(
  params?: Signal<BerryFirmnessListParams>,
  options?: OrvalHttpResourceOptions<PaginatedBerryFirmnessSummaryList, unknown>,
): HttpResourceRef<PaginatedBerryFirmnessSummaryList | undefined> {
  return httpResource<PaginatedBerryFirmnessSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/berry-firmness/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function berryFirmnessRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<BerryFirmnessDetail, unknown> & {
    defaultValue: NoInfer<BerryFirmnessDetail>;
  },
): HttpResourceRef<BerryFirmnessDetail>;
export function berryFirmnessRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<BerryFirmnessDetail, unknown>,
): HttpResourceRef<BerryFirmnessDetail | undefined>;
export function berryFirmnessRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<BerryFirmnessDetail, unknown>,
): HttpResourceRef<BerryFirmnessDetail | undefined> {
  return httpResource<BerryFirmnessDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/berry-firmness/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function berryFlavorListResource(
  params: Signal<BerryFlavorListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedBerryFlavorSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedBerryFlavorSummaryList>;
  },
): HttpResourceRef<PaginatedBerryFlavorSummaryList>;
export function berryFlavorListResource(
  params?: Signal<BerryFlavorListParams>,
  options?: OrvalHttpResourceOptions<PaginatedBerryFlavorSummaryList, unknown>,
): HttpResourceRef<PaginatedBerryFlavorSummaryList | undefined>;
export function berryFlavorListResource(
  params?: Signal<BerryFlavorListParams>,
  options?: OrvalHttpResourceOptions<PaginatedBerryFlavorSummaryList, unknown>,
): HttpResourceRef<PaginatedBerryFlavorSummaryList | undefined> {
  return httpResource<PaginatedBerryFlavorSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/berry-flavor/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function berryFlavorRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<BerryFlavorDetail, unknown> & {
    defaultValue: NoInfer<BerryFlavorDetail>;
  },
): HttpResourceRef<BerryFlavorDetail>;
export function berryFlavorRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<BerryFlavorDetail, unknown>,
): HttpResourceRef<BerryFlavorDetail | undefined>;
export function berryFlavorRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<BerryFlavorDetail, unknown>,
): HttpResourceRef<BerryFlavorDetail | undefined> {
  return httpResource<BerryFlavorDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/berry-flavor/${id()}/`, options),
    options,
  );
}

export type BerryListResourceResult = NonNullable<PaginatedBerrySummaryList>;
export type BerryRetrieveResourceResult = NonNullable<BerryDetail>;
export type BerryFirmnessListResourceResult = NonNullable<PaginatedBerryFirmnessSummaryList>;
export type BerryFirmnessRetrieveResourceResult = NonNullable<BerryFirmnessDetail>;
export type BerryFlavorListResourceResult = NonNullable<PaginatedBerryFlavorSummaryList>;
export type BerryFlavorRetrieveResourceResult = NonNullable<BerryFlavorDetail>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
