/**
 * Curated "where does it spawn" lookup for the Pokédex.
 *
 * PokeAPI has no reverse lookup (species -> location-areas), so this static
 * map powers the instant "Found in" chips for the most famous habitats. Areas
 * the player has actually explored are appended live by PokeDataService.
 * Keys are lowercase species names (PokeAPI slugs).
 */
export const KNOWN_HABITATS: Record<string, string[]> = {
  bulbasaur: ['Viridian Forest', 'Route 2'],
  ivysaur: ['Safari Zone'],
  venusaur: ['Safari Zone'],
  charmander: ['Route 3', 'Rock Tunnel'],
  charmeleon: ['Rock Tunnel', 'Victory Road'],
  charizard: ['Victory Road'],
  squirtle: ['Route 4', 'Seafoam Islands'],
  wartortle: ['Seafoam Islands', 'Route 19'],
  blastoise: ['Seafoam Islands'],
  caterpie: ['Viridian Forest', 'Route 2'],
  metapod: ['Viridian Forest'],
  butterfree: ['Viridian Forest', 'Safari Zone'],
  weedle: ['Viridian Forest', 'Route 2'],
  kakuna: ['Viridian Forest'],
  beedrill: ['Viridian Forest', 'Safari Zone'],
  pidgey: ['Route 1', 'Route 2', 'Viridian Forest'],
  pidgeotto: ['Route 12', 'Route 13'],
  pidgeot: ['Route 15', 'Route 16'],
  rattata: ['Route 1', 'Route 2', 'Route 3'],
  raticate: ['Route 13', 'Route 14', 'Route 15'],
  spearow: ['Route 3', 'Route 4'],
  fearow: ['Route 12', 'Route 13'],
  ekans: ['Route 3', 'Route 4'],
  arbok: ['Safari Zone', 'Route 23'],
  pikachu: ['Viridian Forest', 'Power Plant'],
  raichu: ['Power Plant'],
  sandshrew: ['Route 3', 'Route 4', 'Mount Moon'],
  sandslash: ['Victory Road'],
  nidoranf: ['Route 2', 'Route 9', 'Mount Moon'],
  nidoranm: ['Route 2', 'Route 9', 'Mount Moon'],
  nidorina: ['Route 9', 'Safari Zone'],
  nidorino: ['Route 9', 'Safari Zone'],
  clefairy: ['Mount Moon'],
  clefable: ['Mount Moon'],
  vulpix: ['Route 7', 'Route 8', 'Pokemon Mansion'],
  ninetales: ['Pokemon Mansion'],
  jigglypuff: ['Route 3', 'Route 4'],
  wigglytuff: ['Route 12'],
  zubat: ['Mount Moon', 'Rock Tunnel', 'Seafoam Islands'],
  golbat: ['Victory Road', 'Cerulean Cave'],
  oddish: ['Route 5', 'Route 6', 'Route 7'],
  gloom: ['Safari Zone'],
  vileplume: ['Safari Zone'],
  paras: ['Mount Moon', 'Rock Tunnel'],
  parasect: ['Safari Zone'],
  venonat: ['Safari Zone', 'Route 12'],
  venomoth: ['Safari Zone', 'Route 15'],
  diglett: ["Diglett's Cave"],
  dugtrio: ["Diglett's Cave", 'Victory Road'],
  meowth: ['Route 4', 'Route 9'],
  persian: ['Route 17', 'Route 18'],
  psyduck: ['Route 6', 'Route 19', 'Seafoam Islands'],
  golduck: ['Seafoam Islands', 'Cerulean Cave'],
  mankey: ['Route 5', 'Route 6'],
  primeape: ['Victory Road'],
  growlithe: ['Route 7', 'Route 8', 'Pokemon Mansion'],
  arcanine: ['Pokemon Mansion'],
  poliwag: ['Route 6', 'Route 22', 'Route 23'],
  poliwhirl: ['Seafoam Islands'],
  poliwrath: ['Cerulean Cave'],
  abra: ['Route 5', 'Route 6', 'Route 7', 'Route 8'],
  kadabra: ['Cerulean Cave'],
  alakazam: ['Cerulean Cave'],
  machop: ['Rock Tunnel', 'Victory Road'],
  machoke: ['Victory Road'],
  machamp: ['Cerulean Cave'],
  bellsprout: ['Route 5', 'Route 6', 'Route 7'],
  weepinbell: ['Safari Zone'],
  victreebel: ['Safari Zone'],
  tentacool: ['Route 19', 'Route 20', 'Route 21', 'Seafoam Islands'],
  tentacruel: ['Seafoam Islands', 'Cerulean Cave'],
  geodude: ['Mount Moon', 'Rock Tunnel', 'Victory Road'],
  graveler: ['Victory Road'],
  golem: ['Victory Road', 'Cerulean Cave'],
  ponyta: ['Route 7', 'Route 8'],
  rapidash: ['Pokemon Mansion'],
  slowpoke: ['Route 12', 'Route 13', 'Seafoam Islands'],
  slowbro: ['Seafoam Islands'],
  magnemite: ['Power Plant'],
  magneton: ['Power Plant', 'Cerulean Cave'],
  farfetchd: ['Route 12', 'Route 13'],
  doduo: ['Route 16', 'Route 17', 'Route 18'],
  dodrio: ['Route 17', 'Route 18'],
  seel: ['Seafoam Islands', 'Route 20'],
  dewgong: ['Seafoam Islands', 'Cerulean Cave'],
  grimer: ['Pokemon Mansion', 'Cerulean Cave'],
  muk: ['Cerulean Cave'],
  shellder: ['Route 19', 'Route 20', 'Route 21'],
  cloyster: ['Seafoam Islands'],
  gastly: ['Pokemon Tower', 'Cerulean Cave'],
  haunter: ['Pokemon Tower', 'Cerulean Cave'],
  gengar: ['Cerulean Cave'],
  onix: ['Mount Moon', 'Rock Tunnel', 'Victory Road'],
  drowzee: ['Route 11', 'Route 12'],
  hypno: ['Safari Zone'],
  krabby: ['Route 19', 'Route 20', 'Route 21'],
  kingler: ['Seafoam Islands'],
  voltorb: ['Power Plant'],
  electrode: ['Power Plant', 'Cerulean Cave'],
  exeggcute: ['Safari Zone', 'Route 12'],
  exeggutor: ['Safari Zone'],
  cubone: ['Pokemon Tower', 'Safari Zone'],
  marowak: ['Pokemon Tower', 'Victory Road'],
  hitmonlee: ['Saffron City'],
  hitmonchan: ['Saffron City'],
  lickitung: ['Safari Zone'],
  koffing: ['Pokemon Mansion', 'Cerulean Cave'],
  weezing: ['Cerulean Cave'],
  rhyhorn: ['Safari Zone', 'Victory Road'],
  rhydon: ['Victory Road', 'Cerulean Cave'],
  chansey: ['Safari Zone'],
  tangela: ['Safari Zone'],
  kangaskhan: ['Safari Zone'],
  horsea: ['Route 19', 'Route 20', 'Route 21'],
  seadra: ['Seafoam Islands'],
  goldeen: ['Route 6', 'Route 12', 'Route 13'],
  seaking: ['Seafoam Islands'],
  staryu: ['Route 19', 'Route 20', 'Route 21'],
  starmie: ['Seafoam Islands', 'Cerulean Cave'],
  mr_mime: ['Route 12', 'Route 13'],
  scyther: ['Safari Zone'],
  jynx: ['Route 15', 'Seafoam Islands'],
  electabuzz: ['Power Plant'],
  magmar: ['Pokemon Mansion'],
  pinsir: ['Safari Zone'],
  tauros: ['Safari Zone'],
  magikarp: ['Route 4', 'Route 12', 'Route 19', 'Route 20', 'Route 21'],
  gyarados: ['Cerulean Cave'],
  lapras: ['Silph Co.', 'Union Cave'],
  ditto: ['Pokemon Mansion', 'Cerulean Cave'],
  eevee: ['Celadon City'],
  vaporeon: ['Evolution'],
  jolteon: ['Evolution'],
  flareon: ['Evolution'],
  porygon: ['Celadon City Game Corner'],
  omanyte: ['Fossil'],
  omastar: ['Evolution'],
  kabuto: ['Fossil'],
  kabutops: ['Evolution'],
  aerodactyl: ['Fossil'],
  snorlax: ['Route 12', 'Route 16'],
  articuno: ['Seafoam Islands'],
  zapdos: ['Power Plant'],
  moltres: ['Victory Road'],
  dratini: ['Safari Zone', 'Dragons Den'],
  dragonair: ['Dragons Den'],
  dragonite: ['Dragons Den'],
  mewtwo: ['Cerulean Cave'],
  mew: ['Event'],
  chikorita: ['Ilex Forest', 'Route 29'],
  cyndaquil: ['Route 31', 'Sprout Tower'],
  totodile: ['Route 32', 'Ruins of Alph'],
  hoothoot: ['Route 1 (Johto)', 'Route 37'],
  ledyba: ['Ilex Forest', 'Route 31'],
  marill: ['Route 32', 'Mt. Mortar'],
  sudowoodo: ['Route 36'],
  espeon: ['Evolution'],
  umbreon: ['Evolution'],
  steelix: ['Mt. Mortar', 'Cliff Cave'],
  scizor: ['Evolution'],
  tyranitar: ['Victory Road (Kanto)', 'Mount Silver'],
  lugia: ['Whirl Islands'],
  'ho-oh': ['Tin Tower'],
  celebi: ['Ilex Forest Shrine'],
};

/** Curated "Found in" names for a species (empty when unknown). */
export function knownHabitatsFor(name: string): string[] {
  const key = name.toLowerCase();
  return KNOWN_HABITATS[key] ?? [];
}
