/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import { HttpHeaders, httpResource } from '@angular/common/http';
import type {
  HttpContext,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest,
} from '@angular/common/http';

import type { ResourceStatus, Signal } from '@angular/core';

import type {
  MoveAilmentListParams,
  MoveBattleStyleDetail,
  MoveBattleStyleListParams,
  MoveCategoryListParams,
  MoveDetail,
  MoveLearnMethodDetail,
  MoveLearnMethodListParams,
  MoveListParams,
  MoveMetaAilmentDetail,
  MoveMetaCategoryDetail,
  MoveTargetDetail,
  MoveTargetListParams,
  PaginatedMoveBattleStyleSummaryList,
  PaginatedMoveLearnMethodSummaryList,
  PaginatedMoveMetaAilmentSummaryList,
  PaginatedMoveMetaCategorySummaryList,
  PaginatedMoveSummaryList,
  PaginatedMoveTargetSummaryList,
} from '@poke/poke-api/model';

export interface OrvalHttpResourceRequestExtension {
  /** Extra headers merged over generated headers. Pass a function to read signals reactively. */
  headers?: HttpResourceRequest['headers'] | (() => HttpResourceRequest['headers']);
  /** Angular HttpContext forwarded to the underlying request. Pass a function to derive it reactively. */
  context?: HttpContext | (() => HttpContext);
  /** Last-resort escape hatch: transform the final request descriptor. Runs inside the resource's reactive context. */
  request?: (request: HttpResourceRequest) => HttpResourceRequest;
}

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = (TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>) &
  OrvalHttpResourceRequestExtension;

function mergeOrvalResourceHeaders(
  base: HttpResourceRequest['headers'],
  extra: HttpResourceRequest['headers'],
): HttpResourceRequest['headers'] {
  if (!base) return extra;
  if (!extra) return base;
  if (base instanceof HttpHeaders || extra instanceof HttpHeaders) {
    const toHeaderValue = (value: string | readonly string[]): string | string[] =>
      Array.isArray(value) ? Array.from(value, String) : String(value);
    let merged =
      base instanceof HttpHeaders
        ? base
        : Object.entries(base).reduce(
            (headers, [key, value]) => headers.set(key, toHeaderValue(value)),
            new HttpHeaders(),
          );
    const extraRecord =
      extra instanceof HttpHeaders
        ? extra.keys().reduce<Record<string, string[]>>((record, key) => {
            const values = extra.getAll(key);
            if (values) record[key] = values;
            return record;
          }, {})
        : extra;
    for (const [key, value] of Object.entries(extraRecord)) {
      merged = merged.set(key, toHeaderValue(value));
    }
    return merged;
  }
  return { ...base, ...extra };
}

export function applyOrvalRequestExtension(
  request: string | HttpResourceRequest,
  options?: OrvalHttpResourceRequestExtension,
): HttpResourceRequest {
  const base: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
  if (
    !options ||
    (options.headers === undefined &&
      options.context === undefined &&
      options.request === undefined)
  ) {
    return base;
  }
  let next: HttpResourceRequest = { ...base };
  const extraHeaders = typeof options.headers === 'function' ? options.headers() : options.headers;
  if (extraHeaders !== undefined) {
    next = { ...next, headers: mergeOrvalResourceHeaders(next.headers, extraHeaders) };
  }
  const context = typeof options.context === 'function' ? options.context() : options.context;
  if (context !== undefined) {
    next = { ...next, context };
  }
  return options.request ? options.request(next) : next;
}

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveListResource(
  params: Signal<MoveListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedMoveSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedMoveSummaryList>;
  },
): HttpResourceRef<PaginatedMoveSummaryList>;
export function moveListResource(
  params?: Signal<MoveListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveSummaryList | undefined>;
export function moveListResource(
  params?: Signal<MoveListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveSummaryList | undefined> {
  return httpResource<PaginatedMoveSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/move/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<MoveDetail, unknown> & { defaultValue: NoInfer<MoveDetail> },
): HttpResourceRef<MoveDetail>;
export function moveRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveDetail, unknown>,
): HttpResourceRef<MoveDetail | undefined>;
export function moveRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveDetail, unknown>,
): HttpResourceRef<MoveDetail | undefined> {
  return httpResource<MoveDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/move/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveAilmentListResource(
  params: Signal<MoveAilmentListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedMoveMetaAilmentSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedMoveMetaAilmentSummaryList>;
  },
): HttpResourceRef<PaginatedMoveMetaAilmentSummaryList>;
export function moveAilmentListResource(
  params?: Signal<MoveAilmentListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveMetaAilmentSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveMetaAilmentSummaryList | undefined>;
export function moveAilmentListResource(
  params?: Signal<MoveAilmentListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveMetaAilmentSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveMetaAilmentSummaryList | undefined> {
  return httpResource<PaginatedMoveMetaAilmentSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/move-ailment/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveAilmentRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<MoveMetaAilmentDetail, unknown> & {
    defaultValue: NoInfer<MoveMetaAilmentDetail>;
  },
): HttpResourceRef<MoveMetaAilmentDetail>;
export function moveAilmentRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveMetaAilmentDetail, unknown>,
): HttpResourceRef<MoveMetaAilmentDetail | undefined>;
export function moveAilmentRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveMetaAilmentDetail, unknown>,
): HttpResourceRef<MoveMetaAilmentDetail | undefined> {
  return httpResource<MoveMetaAilmentDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/move-ailment/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveBattleStyleListResource(
  params: Signal<MoveBattleStyleListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedMoveBattleStyleSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedMoveBattleStyleSummaryList>;
  },
): HttpResourceRef<PaginatedMoveBattleStyleSummaryList>;
export function moveBattleStyleListResource(
  params?: Signal<MoveBattleStyleListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveBattleStyleSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveBattleStyleSummaryList | undefined>;
export function moveBattleStyleListResource(
  params?: Signal<MoveBattleStyleListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveBattleStyleSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveBattleStyleSummaryList | undefined> {
  return httpResource<PaginatedMoveBattleStyleSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/move-battle-style/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveBattleStyleRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<MoveBattleStyleDetail, unknown> & {
    defaultValue: NoInfer<MoveBattleStyleDetail>;
  },
): HttpResourceRef<MoveBattleStyleDetail>;
export function moveBattleStyleRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveBattleStyleDetail, unknown>,
): HttpResourceRef<MoveBattleStyleDetail | undefined>;
export function moveBattleStyleRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveBattleStyleDetail, unknown>,
): HttpResourceRef<MoveBattleStyleDetail | undefined> {
  return httpResource<MoveBattleStyleDetail>(
    () =>
      applyOrvalRequestExtension(`https://pokeapi.co/api/v2/move-battle-style/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveCategoryListResource(
  params: Signal<MoveCategoryListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedMoveMetaCategorySummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedMoveMetaCategorySummaryList>;
  },
): HttpResourceRef<PaginatedMoveMetaCategorySummaryList>;
export function moveCategoryListResource(
  params?: Signal<MoveCategoryListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveMetaCategorySummaryList, unknown>,
): HttpResourceRef<PaginatedMoveMetaCategorySummaryList | undefined>;
export function moveCategoryListResource(
  params?: Signal<MoveCategoryListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveMetaCategorySummaryList, unknown>,
): HttpResourceRef<PaginatedMoveMetaCategorySummaryList | undefined> {
  return httpResource<PaginatedMoveMetaCategorySummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/move-category/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveCategoryRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<MoveMetaCategoryDetail, unknown> & {
    defaultValue: NoInfer<MoveMetaCategoryDetail>;
  },
): HttpResourceRef<MoveMetaCategoryDetail>;
export function moveCategoryRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveMetaCategoryDetail, unknown>,
): HttpResourceRef<MoveMetaCategoryDetail | undefined>;
export function moveCategoryRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveMetaCategoryDetail, unknown>,
): HttpResourceRef<MoveMetaCategoryDetail | undefined> {
  return httpResource<MoveMetaCategoryDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/move-category/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveLearnMethodListResource(
  params: Signal<MoveLearnMethodListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedMoveLearnMethodSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedMoveLearnMethodSummaryList>;
  },
): HttpResourceRef<PaginatedMoveLearnMethodSummaryList>;
export function moveLearnMethodListResource(
  params?: Signal<MoveLearnMethodListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveLearnMethodSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveLearnMethodSummaryList | undefined>;
export function moveLearnMethodListResource(
  params?: Signal<MoveLearnMethodListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveLearnMethodSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveLearnMethodSummaryList | undefined> {
  return httpResource<PaginatedMoveLearnMethodSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/move-learn-method/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveLearnMethodRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<MoveLearnMethodDetail, unknown> & {
    defaultValue: NoInfer<MoveLearnMethodDetail>;
  },
): HttpResourceRef<MoveLearnMethodDetail>;
export function moveLearnMethodRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveLearnMethodDetail, unknown>,
): HttpResourceRef<MoveLearnMethodDetail | undefined>;
export function moveLearnMethodRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveLearnMethodDetail, unknown>,
): HttpResourceRef<MoveLearnMethodDetail | undefined> {
  return httpResource<MoveLearnMethodDetail>(
    () =>
      applyOrvalRequestExtension(`https://pokeapi.co/api/v2/move-learn-method/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveTargetListResource(
  params: Signal<MoveTargetListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedMoveTargetSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedMoveTargetSummaryList>;
  },
): HttpResourceRef<PaginatedMoveTargetSummaryList>;
export function moveTargetListResource(
  params?: Signal<MoveTargetListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveTargetSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveTargetSummaryList | undefined>;
export function moveTargetListResource(
  params?: Signal<MoveTargetListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveTargetSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveTargetSummaryList | undefined> {
  return httpResource<PaginatedMoveTargetSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/move-target/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveTargetRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<MoveTargetDetail, unknown> & {
    defaultValue: NoInfer<MoveTargetDetail>;
  },
): HttpResourceRef<MoveTargetDetail>;
export function moveTargetRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveTargetDetail, unknown>,
): HttpResourceRef<MoveTargetDetail | undefined>;
export function moveTargetRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveTargetDetail, unknown>,
): HttpResourceRef<MoveTargetDetail | undefined> {
  return httpResource<MoveTargetDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/move-target/${id()}/`, options),
    options,
  );
}

export type MoveListResourceResult = NonNullable<PaginatedMoveSummaryList>;
export type MoveRetrieveResourceResult = NonNullable<MoveDetail>;
export type MoveAilmentListResourceResult = NonNullable<PaginatedMoveMetaAilmentSummaryList>;
export type MoveAilmentRetrieveResourceResult = NonNullable<MoveMetaAilmentDetail>;
export type MoveBattleStyleListResourceResult = NonNullable<PaginatedMoveBattleStyleSummaryList>;
export type MoveBattleStyleRetrieveResourceResult = NonNullable<MoveBattleStyleDetail>;
export type MoveCategoryListResourceResult = NonNullable<PaginatedMoveMetaCategorySummaryList>;
export type MoveCategoryRetrieveResourceResult = NonNullable<MoveMetaCategoryDetail>;
export type MoveLearnMethodListResourceResult = NonNullable<PaginatedMoveLearnMethodSummaryList>;
export type MoveLearnMethodRetrieveResourceResult = NonNullable<MoveLearnMethodDetail>;
export type MoveTargetListResourceResult = NonNullable<PaginatedMoveTargetSummaryList>;
export type MoveTargetRetrieveResourceResult = NonNullable<MoveTargetDetail>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
