/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import { HttpHeaders, httpResource } from '@angular/common/http';
import type {
  HttpContext,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest,
} from '@angular/common/http';

import type { ResourceStatus, Signal } from '@angular/core';

import type {
  CurrencyDetail,
  CurrencyListParams,
  ItemAttributeDetail,
  ItemAttributeListParams,
  ItemCategoryDetail,
  ItemCategoryListParams,
  ItemDetail,
  ItemFlingEffectDetail,
  ItemFlingEffectListParams,
  ItemListParams,
  ItemPocketDetail,
  ItemPocketListParams,
  PaginatedCurrencySummaryList,
  PaginatedItemAttributeSummaryList,
  PaginatedItemCategorySummaryList,
  PaginatedItemFlingEffectSummaryList,
  PaginatedItemPocketSummaryList,
  PaginatedItemSummaryList,
} from '@poke/poke-api/model';

export interface OrvalHttpResourceRequestExtension {
  /** Extra headers merged over generated headers. Pass a function to read signals reactively. */
  headers?: HttpResourceRequest['headers'] | (() => HttpResourceRequest['headers']);
  /** Angular HttpContext forwarded to the underlying request. Pass a function to derive it reactively. */
  context?: HttpContext | (() => HttpContext);
  /** Last-resort escape hatch: transform the final request descriptor. Runs inside the resource's reactive context. */
  request?: (request: HttpResourceRequest) => HttpResourceRequest;
}

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = (TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>) &
  OrvalHttpResourceRequestExtension;

function mergeOrvalResourceHeaders(
  base: HttpResourceRequest['headers'],
  extra: HttpResourceRequest['headers'],
): HttpResourceRequest['headers'] {
  if (!base) return extra;
  if (!extra) return base;
  if (base instanceof HttpHeaders || extra instanceof HttpHeaders) {
    const toHeaderValue = (value: string | readonly string[]): string | string[] =>
      Array.isArray(value) ? Array.from(value, String) : String(value);
    let merged =
      base instanceof HttpHeaders
        ? base
        : Object.entries(base).reduce(
            (headers, [key, value]) => headers.set(key, toHeaderValue(value)),
            new HttpHeaders(),
          );
    const extraRecord =
      extra instanceof HttpHeaders
        ? extra.keys().reduce<Record<string, string[]>>((record, key) => {
            const values = extra.getAll(key);
            if (values) record[key] = values;
            return record;
          }, {})
        : extra;
    for (const [key, value] of Object.entries(extraRecord)) {
      merged = merged.set(key, toHeaderValue(value));
    }
    return merged;
  }
  return { ...base, ...extra };
}

export function applyOrvalRequestExtension(
  request: string | HttpResourceRequest,
  options?: OrvalHttpResourceRequestExtension,
): HttpResourceRequest {
  const base: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
  if (
    !options ||
    (options.headers === undefined &&
      options.context === undefined &&
      options.request === undefined)
  ) {
    return base;
  }
  let next: HttpResourceRequest = { ...base };
  const extraHeaders = typeof options.headers === 'function' ? options.headers() : options.headers;
  if (extraHeaders !== undefined) {
    next = { ...next, headers: mergeOrvalResourceHeaders(next.headers, extraHeaders) };
  }
  const context = typeof options.context === 'function' ? options.context() : options.context;
  if (context !== undefined) {
    next = { ...next, context };
  }
  return options.request ? options.request(next) : next;
}

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemListResource(
  params: Signal<ItemListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedItemSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedItemSummaryList>;
  },
): HttpResourceRef<PaginatedItemSummaryList>;
export function itemListResource(
  params?: Signal<ItemListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemSummaryList, unknown>,
): HttpResourceRef<PaginatedItemSummaryList | undefined>;
export function itemListResource(
  params?: Signal<ItemListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemSummaryList, unknown>,
): HttpResourceRef<PaginatedItemSummaryList | undefined> {
  return httpResource<PaginatedItemSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/item/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<ItemDetail, unknown> & { defaultValue: NoInfer<ItemDetail> },
): HttpResourceRef<ItemDetail>;
export function itemRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemDetail, unknown>,
): HttpResourceRef<ItemDetail | undefined>;
export function itemRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemDetail, unknown>,
): HttpResourceRef<ItemDetail | undefined> {
  return httpResource<ItemDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/item/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemCategoryListResource(
  params: Signal<ItemCategoryListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedItemCategorySummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedItemCategorySummaryList>;
  },
): HttpResourceRef<PaginatedItemCategorySummaryList>;
export function itemCategoryListResource(
  params?: Signal<ItemCategoryListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemCategorySummaryList, unknown>,
): HttpResourceRef<PaginatedItemCategorySummaryList | undefined>;
export function itemCategoryListResource(
  params?: Signal<ItemCategoryListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemCategorySummaryList, unknown>,
): HttpResourceRef<PaginatedItemCategorySummaryList | undefined> {
  return httpResource<PaginatedItemCategorySummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/item-category/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemCategoryRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<ItemCategoryDetail, unknown> & {
    defaultValue: NoInfer<ItemCategoryDetail>;
  },
): HttpResourceRef<ItemCategoryDetail>;
export function itemCategoryRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemCategoryDetail, unknown>,
): HttpResourceRef<ItemCategoryDetail | undefined>;
export function itemCategoryRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemCategoryDetail, unknown>,
): HttpResourceRef<ItemCategoryDetail | undefined> {
  return httpResource<ItemCategoryDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/item-category/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemAttributeListResource(
  params: Signal<ItemAttributeListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedItemAttributeSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedItemAttributeSummaryList>;
  },
): HttpResourceRef<PaginatedItemAttributeSummaryList>;
export function itemAttributeListResource(
  params?: Signal<ItemAttributeListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemAttributeSummaryList, unknown>,
): HttpResourceRef<PaginatedItemAttributeSummaryList | undefined>;
export function itemAttributeListResource(
  params?: Signal<ItemAttributeListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemAttributeSummaryList, unknown>,
): HttpResourceRef<PaginatedItemAttributeSummaryList | undefined> {
  return httpResource<PaginatedItemAttributeSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/item-attribute/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemAttributeRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<ItemAttributeDetail, unknown> & {
    defaultValue: NoInfer<ItemAttributeDetail>;
  },
): HttpResourceRef<ItemAttributeDetail>;
export function itemAttributeRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemAttributeDetail, unknown>,
): HttpResourceRef<ItemAttributeDetail | undefined>;
export function itemAttributeRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemAttributeDetail, unknown>,
): HttpResourceRef<ItemAttributeDetail | undefined> {
  return httpResource<ItemAttributeDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/item-attribute/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemFlingEffectListResource(
  params: Signal<ItemFlingEffectListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedItemFlingEffectSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedItemFlingEffectSummaryList>;
  },
): HttpResourceRef<PaginatedItemFlingEffectSummaryList>;
export function itemFlingEffectListResource(
  params?: Signal<ItemFlingEffectListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemFlingEffectSummaryList, unknown>,
): HttpResourceRef<PaginatedItemFlingEffectSummaryList | undefined>;
export function itemFlingEffectListResource(
  params?: Signal<ItemFlingEffectListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemFlingEffectSummaryList, unknown>,
): HttpResourceRef<PaginatedItemFlingEffectSummaryList | undefined> {
  return httpResource<PaginatedItemFlingEffectSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/item-fling-effect/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemFlingEffectRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<ItemFlingEffectDetail, unknown> & {
    defaultValue: NoInfer<ItemFlingEffectDetail>;
  },
): HttpResourceRef<ItemFlingEffectDetail>;
export function itemFlingEffectRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemFlingEffectDetail, unknown>,
): HttpResourceRef<ItemFlingEffectDetail | undefined>;
export function itemFlingEffectRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemFlingEffectDetail, unknown>,
): HttpResourceRef<ItemFlingEffectDetail | undefined> {
  return httpResource<ItemFlingEffectDetail>(
    () =>
      applyOrvalRequestExtension(`https://pokeapi.co/api/v2/item-fling-effect/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemPocketListResource(
  params: Signal<ItemPocketListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedItemPocketSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedItemPocketSummaryList>;
  },
): HttpResourceRef<PaginatedItemPocketSummaryList>;
export function itemPocketListResource(
  params?: Signal<ItemPocketListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemPocketSummaryList, unknown>,
): HttpResourceRef<PaginatedItemPocketSummaryList | undefined>;
export function itemPocketListResource(
  params?: Signal<ItemPocketListParams>,
  options?: OrvalHttpResourceOptions<PaginatedItemPocketSummaryList, unknown>,
): HttpResourceRef<PaginatedItemPocketSummaryList | undefined> {
  return httpResource<PaginatedItemPocketSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/item-pocket/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function itemPocketRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<ItemPocketDetail, unknown> & {
    defaultValue: NoInfer<ItemPocketDetail>;
  },
): HttpResourceRef<ItemPocketDetail>;
export function itemPocketRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemPocketDetail, unknown>,
): HttpResourceRef<ItemPocketDetail | undefined>;
export function itemPocketRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<ItemPocketDetail, unknown>,
): HttpResourceRef<ItemPocketDetail | undefined> {
  return httpResource<ItemPocketDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/item-pocket/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function currencyListResource(
  params: Signal<CurrencyListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedCurrencySummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedCurrencySummaryList>;
  },
): HttpResourceRef<PaginatedCurrencySummaryList>;
export function currencyListResource(
  params?: Signal<CurrencyListParams>,
  options?: OrvalHttpResourceOptions<PaginatedCurrencySummaryList, unknown>,
): HttpResourceRef<PaginatedCurrencySummaryList | undefined>;
export function currencyListResource(
  params?: Signal<CurrencyListParams>,
  options?: OrvalHttpResourceOptions<PaginatedCurrencySummaryList, unknown>,
): HttpResourceRef<PaginatedCurrencySummaryList | undefined> {
  return httpResource<PaginatedCurrencySummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/currency/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function currencyRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<CurrencyDetail, unknown> & {
    defaultValue: NoInfer<CurrencyDetail>;
  },
): HttpResourceRef<CurrencyDetail>;
export function currencyRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<CurrencyDetail, unknown>,
): HttpResourceRef<CurrencyDetail | undefined>;
export function currencyRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<CurrencyDetail, unknown>,
): HttpResourceRef<CurrencyDetail | undefined> {
  return httpResource<CurrencyDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/currency/${id()}/`, options),
    options,
  );
}

export type ItemListResourceResult = NonNullable<PaginatedItemSummaryList>;
export type ItemRetrieveResourceResult = NonNullable<ItemDetail>;
export type ItemCategoryListResourceResult = NonNullable<PaginatedItemCategorySummaryList>;
export type ItemCategoryRetrieveResourceResult = NonNullable<ItemCategoryDetail>;
export type ItemAttributeListResourceResult = NonNullable<PaginatedItemAttributeSummaryList>;
export type ItemAttributeRetrieveResourceResult = NonNullable<ItemAttributeDetail>;
export type ItemFlingEffectListResourceResult = NonNullable<PaginatedItemFlingEffectSummaryList>;
export type ItemFlingEffectRetrieveResourceResult = NonNullable<ItemFlingEffectDetail>;
export type ItemPocketListResourceResult = NonNullable<PaginatedItemPocketSummaryList>;
export type ItemPocketRetrieveResourceResult = NonNullable<ItemPocketDetail>;
export type CurrencyListResourceResult = NonNullable<PaginatedCurrencySummaryList>;
export type CurrencyRetrieveResourceResult = NonNullable<CurrencyDetail>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
