/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { BerryDetailFlavorsItem } from '@poke/poke-api/model/berryDetailFlavorsItem';
import type { BerryFirmnessSummary } from '@poke/poke-api/model/berryFirmnessSummary';
import type { ItemSummary } from '@poke/poke-api/model/itemSummary';
import type { TypeSummary } from '@poke/poke-api/model/typeSummary';

export interface BerryDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  growth_time?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  max_harvest?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  natural_gift_power?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  size?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  smoothness?: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  soil_dryness?: number;
  firmness: BerryFirmnessSummary;
  readonly flavors: readonly BerryDetailFlavorsItem[];
  item: ItemSummary;
  natural_gift_type: TypeSummary;
}
