/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemBaseForm } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemBaseForm';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemEvolvedForm } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemEvolvedForm';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemGender } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemGender';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemHeldItem } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemHeldItem';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemItem } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemItem';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemLocation } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemLocation';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemRegion } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemRegion';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemTrigger } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemTrigger';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemVersionGroup } from '@poke/poke-api/model/evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemVersionGroup';

export type EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItem = {
  version_group: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemVersionGroup;
  is_default: boolean;
  gender: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemGender;
  held_item: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemHeldItem;
  item: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemItem;
  known_move: unknown | null;
  known_move_type: unknown | null;
  location: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemLocation;
  min_affection: number | null;
  min_beauty: number | null;
  min_damage_taken: number | null;
  min_happiness: number | null;
  min_level: number | null;
  min_move_count: number | null;
  min_steps: number | null;
  near_special_rock: boolean | null;
  needs_multiplayer: boolean | null;
  needs_overworld_rain: boolean | null;
  party_species: string | null;
  party_type: string | null;
  relative_physical_stats: string | null;
  time_of_day: string;
  trade_species: string | null;
  trigger: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemTrigger;
  turn_upside_down: boolean;
  used_move: unknown | null;
  region: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemRegion;
  base_form: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemBaseForm;
  evolved_form: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemEvolvedForm;
};
