/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { AbilitySummary } from '@poke/poke-api/model/abilitySummary';
import type { GenerationName } from '@poke/poke-api/model/generationName';
import type { MoveSummary } from '@poke/poke-api/model/moveSummary';
import type { PokemonSpeciesSummary } from '@poke/poke-api/model/pokemonSpeciesSummary';
import type { RegionSummary } from '@poke/poke-api/model/regionSummary';
import type { TypeSummary } from '@poke/poke-api/model/typeSummary';
import type { VersionGroupSummary } from '@poke/poke-api/model/versionGroupSummary';

export interface GenerationDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  readonly abilities: readonly AbilitySummary[];
  main_region: RegionSummary;
  readonly moves: readonly MoveSummary[];
  readonly names: readonly GenerationName[];
  readonly pokemon_species: readonly PokemonSpeciesSummary[];
  readonly types: readonly TypeSummary[];
  readonly version_groups: readonly VersionGroupSummary[];
}
