/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { ItemCategorySummary } from '@poke/poke-api/model/itemCategorySummary';
import type { ItemDetailAttributesItem } from '@poke/poke-api/model/itemDetailAttributesItem';
import type { ItemDetailBabyTriggerFor } from '@poke/poke-api/model/itemDetailBabyTriggerFor';
import type { ItemDetailHeldByPokemonItem } from '@poke/poke-api/model/itemDetailHeldByPokemonItem';
import type { ItemDetailMachinesItem } from '@poke/poke-api/model/itemDetailMachinesItem';
import type { ItemDetailSprites } from '@poke/poke-api/model/itemDetailSprites';
import type { ItemEffectText } from '@poke/poke-api/model/itemEffectText';
import type { ItemFlavorText } from '@poke/poke-api/model/itemFlavorText';
import type { ItemFlingEffectSummary } from '@poke/poke-api/model/itemFlingEffectSummary';
import type { ItemGameIndex } from '@poke/poke-api/model/itemGameIndex';
import type { ItemName } from '@poke/poke-api/model/itemName';
import type { ItemPrice } from '@poke/poke-api/model/itemPrice';

export interface ItemDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  fling_power?: number | null;
  fling_effect: ItemFlingEffectSummary;
  readonly attributes: readonly ItemDetailAttributesItem[];
  category: ItemCategorySummary;
  readonly effect_entries: readonly ItemEffectText[];
  readonly flavor_text_entries: readonly ItemFlavorText[];
  readonly game_indices: readonly ItemGameIndex[];
  readonly prices: readonly ItemPrice[];
  readonly names: readonly ItemName[];
  readonly held_by_pokemon: readonly ItemDetailHeldByPokemonItem[];
  readonly sprites: ItemDetailSprites;
  readonly baby_trigger_for: ItemDetailBabyTriggerFor;
  readonly machines: readonly ItemDetailMachinesItem[];
}
