/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { ContestEffectSummary } from '@poke/poke-api/model/contestEffectSummary';
import type { ContestTypeSummary } from '@poke/poke-api/model/contestTypeSummary';
import type { GenerationSummary } from '@poke/poke-api/model/generationSummary';
import type { MoveChange } from '@poke/poke-api/model/moveChange';
import type { MoveDamageClassSummary } from '@poke/poke-api/model/moveDamageClassSummary';
import type { MoveDetailContestCombos } from '@poke/poke-api/model/moveDetailContestCombos';
import type { MoveDetailEffectChangesItem } from '@poke/poke-api/model/moveDetailEffectChangesItem';
import type { MoveDetailEffectEntriesItem } from '@poke/poke-api/model/moveDetailEffectEntriesItem';
import type { MoveDetailLearnedByPokemonItem } from '@poke/poke-api/model/moveDetailLearnedByPokemonItem';
import type { MoveDetailMachinesItem } from '@poke/poke-api/model/moveDetailMachinesItem';
import type { MoveDetailStatChangesItem } from '@poke/poke-api/model/moveDetailStatChangesItem';
import type { MoveFlavorText } from '@poke/poke-api/model/moveFlavorText';
import type { MoveMeta } from '@poke/poke-api/model/moveMeta';
import type { MoveName } from '@poke/poke-api/model/moveName';
import type { MoveTargetSummary } from '@poke/poke-api/model/moveTargetSummary';
import type { SuperContestEffectSummary } from '@poke/poke-api/model/superContestEffectSummary';
import type { TypeSummary } from '@poke/poke-api/model/typeSummary';

export interface MoveDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  accuracy?: number | null;
  effect_chance: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  pp?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  priority?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  power?: number | null;
  readonly contest_combos: MoveDetailContestCombos;
  contest_type: ContestTypeSummary;
  contest_effect: ContestEffectSummary;
  damage_class: MoveDamageClassSummary;
  readonly effect_entries: readonly MoveDetailEffectEntriesItem[];
  readonly effect_changes: readonly MoveDetailEffectChangesItem[];
  generation: GenerationSummary;
  readonly meta: MoveMeta;
  readonly names: readonly MoveName[];
  readonly past_values: readonly MoveChange[];
  readonly stat_changes: readonly MoveDetailStatChangesItem[];
  super_contest_effect: SuperContestEffectSummary;
  target: MoveTargetSummary;
  type: TypeSummary;
  readonly machines: readonly MoveDetailMachinesItem[];
  readonly flavor_text_entries: readonly MoveFlavorText[];
  readonly learned_by_pokemon: readonly MoveDetailLearnedByPokemonItem[];
}
