/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { EvolutionChainSummary } from '@poke/poke-api/model/evolutionChainSummary';
import type { GenerationSummary } from '@poke/poke-api/model/generationSummary';
import type { GrowthRateSummary } from '@poke/poke-api/model/growthRateSummary';
import type { PokemonColorSummary } from '@poke/poke-api/model/pokemonColorSummary';
import type { PokemonDexEntry } from '@poke/poke-api/model/pokemonDexEntry';
import type { PokemonHabitatSummary } from '@poke/poke-api/model/pokemonHabitatSummary';
import type { PokemonShapeSummary } from '@poke/poke-api/model/pokemonShapeSummary';
import type { PokemonSpeciesDescription } from '@poke/poke-api/model/pokemonSpeciesDescription';
import type { PokemonSpeciesDetailEggGroupsItem } from '@poke/poke-api/model/pokemonSpeciesDetailEggGroupsItem';
import type { PokemonSpeciesDetailGeneraItem } from '@poke/poke-api/model/pokemonSpeciesDetailGeneraItem';
import type { PokemonSpeciesDetailNamesItem } from '@poke/poke-api/model/pokemonSpeciesDetailNamesItem';
import type { PokemonSpeciesDetailPalParkEncountersItem } from '@poke/poke-api/model/pokemonSpeciesDetailPalParkEncountersItem';
import type { PokemonSpeciesDetailVarietiesItem } from '@poke/poke-api/model/pokemonSpeciesDetailVarietiesItem';
import type { PokemonSpeciesFlavorText } from '@poke/poke-api/model/pokemonSpeciesFlavorText';
import type { PokemonSpeciesSummary } from '@poke/poke-api/model/pokemonSpeciesSummary';

export interface PokemonSpeciesDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  order?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  gender_rate?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  capture_rate?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  base_happiness?: number | null;
  is_baby?: boolean;
  is_legendary?: boolean;
  is_mythical?: boolean;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  hatch_counter?: number | null;
  has_gender_differences?: boolean;
  forms_switchable?: boolean;
  growth_rate: GrowthRateSummary;
  readonly pokedex_numbers: readonly PokemonDexEntry[];
  readonly egg_groups: readonly PokemonSpeciesDetailEggGroupsItem[];
  color: PokemonColorSummary;
  shape: PokemonShapeSummary;
  evolves_from_species: PokemonSpeciesSummary;
  evolution_chain: EvolutionChainSummary;
  habitat: PokemonHabitatSummary;
  generation: GenerationSummary;
  readonly names: readonly PokemonSpeciesDetailNamesItem[];
  readonly pal_park_encounters: readonly PokemonSpeciesDetailPalParkEncountersItem[];
  readonly form_descriptions: readonly PokemonSpeciesDescription[];
  readonly flavor_text_entries: readonly PokemonSpeciesFlavorText[];
  readonly genera: readonly PokemonSpeciesDetailGeneraItem[];
  readonly varieties: readonly PokemonSpeciesDetailVarietiesItem[];
}
