/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { PokemonDetailAbilitiesItem } from '@poke/poke-api/model/pokemonDetailAbilitiesItem';
import type { PokemonDetailCries } from '@poke/poke-api/model/pokemonDetailCries';
import type { PokemonDetailHeldItemsItem } from '@poke/poke-api/model/pokemonDetailHeldItemsItem';
import type { PokemonDetailMovesItem } from '@poke/poke-api/model/pokemonDetailMovesItem';
import type { PokemonDetailPastAbilitiesItem } from '@poke/poke-api/model/pokemonDetailPastAbilitiesItem';
import type { PokemonDetailPastStatsItem } from '@poke/poke-api/model/pokemonDetailPastStatsItem';
import type { PokemonDetailPastTypesItem } from '@poke/poke-api/model/pokemonDetailPastTypesItem';
import type { PokemonDetailSprites } from '@poke/poke-api/model/pokemonDetailSprites';
import type { PokemonDetailTypesItem } from '@poke/poke-api/model/pokemonDetailTypesItem';
import type { PokemonFormSummary } from '@poke/poke-api/model/pokemonFormSummary';
import type { PokemonGameIndex } from '@poke/poke-api/model/pokemonGameIndex';
import type { PokemonSpeciesSummary } from '@poke/poke-api/model/pokemonSpeciesSummary';
import type { PokemonStat } from '@poke/poke-api/model/pokemonStat';

export interface PokemonDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  base_experience?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  height?: number | null;
  is_default?: boolean;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  order?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  weight?: number | null;
  readonly abilities: readonly PokemonDetailAbilitiesItem[];
  readonly past_abilities: readonly PokemonDetailPastAbilitiesItem[];
  readonly forms: readonly PokemonFormSummary[];
  readonly game_indices: readonly PokemonGameIndex[];
  readonly held_items: readonly PokemonDetailHeldItemsItem[];
  readonly location_area_encounters: string;
  readonly moves: readonly PokemonDetailMovesItem[];
  species: PokemonSpeciesSummary;
  readonly sprites: PokemonDetailSprites;
  readonly cries: PokemonDetailCries;
  readonly stats: readonly PokemonStat[];
  readonly past_stats: readonly PokemonDetailPastStatsItem[];
  readonly types: readonly PokemonDetailTypesItem[];
  readonly past_types: readonly PokemonDetailPastTypesItem[];
}
