/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { CharacteristicSummary } from '@poke/poke-api/model/characteristicSummary';
import type { MoveDamageClassSummary } from '@poke/poke-api/model/moveDamageClassSummary';
import type { StatDetailAffectingItemsItem } from '@poke/poke-api/model/statDetailAffectingItemsItem';
import type { StatDetailAffectingMoves } from '@poke/poke-api/model/statDetailAffectingMoves';
import type { StatDetailAffectingNatures } from '@poke/poke-api/model/statDetailAffectingNatures';
import type { StatName } from '@poke/poke-api/model/statName';

export interface StatDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  game_index: number;
  is_battle_only?: boolean;
  readonly affecting_moves: StatDetailAffectingMoves;
  readonly affecting_natures: StatDetailAffectingNatures;
  readonly affecting_items: readonly StatDetailAffectingItemsItem[];
  readonly characteristics: readonly CharacteristicSummary[];
  move_damage_class: MoveDamageClassSummary;
  readonly names: readonly StatName[];
}
