/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { TypeDetailPastDamageRelationsItemDamageRelationsDoubleDamageFromItem } from '@poke/poke-api/model/typeDetailPastDamageRelationsItemDamageRelationsDoubleDamageFromItem';
import type { TypeDetailPastDamageRelationsItemDamageRelationsDoubleDamageToItem } from '@poke/poke-api/model/typeDetailPastDamageRelationsItemDamageRelationsDoubleDamageToItem';
import type { TypeDetailPastDamageRelationsItemDamageRelationsHalfDamageFromItem } from '@poke/poke-api/model/typeDetailPastDamageRelationsItemDamageRelationsHalfDamageFromItem';
import type { TypeDetailPastDamageRelationsItemDamageRelationsHalfDamageToItem } from '@poke/poke-api/model/typeDetailPastDamageRelationsItemDamageRelationsHalfDamageToItem';
import type { TypeDetailPastDamageRelationsItemDamageRelationsNoDamageFromItem } from '@poke/poke-api/model/typeDetailPastDamageRelationsItemDamageRelationsNoDamageFromItem';
import type { TypeDetailPastDamageRelationsItemDamageRelationsNoDamageToItem } from '@poke/poke-api/model/typeDetailPastDamageRelationsItemDamageRelationsNoDamageToItem';

export type TypeDetailPastDamageRelationsItemDamageRelations = {
  no_damage_to: TypeDetailPastDamageRelationsItemDamageRelationsNoDamageToItem[];
  half_damage_to: TypeDetailPastDamageRelationsItemDamageRelationsHalfDamageToItem[];
  double_damage_to: TypeDetailPastDamageRelationsItemDamageRelationsDoubleDamageToItem[];
  no_damage_from: TypeDetailPastDamageRelationsItemDamageRelationsNoDamageFromItem[];
  half_damage_from: TypeDetailPastDamageRelationsItemDamageRelationsHalfDamageFromItem[];
  double_damage_from: TypeDetailPastDamageRelationsItemDamageRelationsDoubleDamageFromItem[];
};
