/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { AbilityName } from '@poke/poke-api/model/abilityName';
import type { GenerationSummary } from '@poke/poke-api/model/generationSummary';
import type { MoveDamageClassSummary } from '@poke/poke-api/model/moveDamageClassSummary';
import type { MoveSummary } from '@poke/poke-api/model/moveSummary';
import type { TypeDetailDamageRelations } from '@poke/poke-api/model/typeDetailDamageRelations';
import type { TypeDetailPastDamageRelationsItem } from '@poke/poke-api/model/typeDetailPastDamageRelationsItem';
import type { TypeDetailPokemonItem } from '@poke/poke-api/model/typeDetailPokemonItem';
import type { TypeDetailSprites } from '@poke/poke-api/model/typeDetailSprites';
import type { TypeGameIndex } from '@poke/poke-api/model/typeGameIndex';

/**
 * Serializer for the Type resource
 */
export interface TypeDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  readonly damage_relations: TypeDetailDamageRelations;
  readonly past_damage_relations: readonly TypeDetailPastDamageRelationsItem[];
  readonly game_indices: readonly TypeGameIndex[];
  generation: GenerationSummary;
  move_damage_class: MoveDamageClassSummary;
  readonly names: readonly AbilityName[];
  readonly pokemon: readonly TypeDetailPokemonItem[];
  readonly moves: readonly MoveSummary[];
  readonly sprites: TypeDetailSprites;
}
