/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import type { GenerationSummary } from '@poke/poke-api/model/generationSummary';
import type { VersionGroupDetailMoveLearnMethodsItem } from '@poke/poke-api/model/versionGroupDetailMoveLearnMethodsItem';
import type { VersionGroupDetailPokedexesItem } from '@poke/poke-api/model/versionGroupDetailPokedexesItem';
import type { VersionGroupDetailRegionsItem } from '@poke/poke-api/model/versionGroupDetailRegionsItem';
import type { VersionSummary } from '@poke/poke-api/model/versionSummary';

export interface VersionGroupDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  order?: number | null;
  generation: GenerationSummary;
  readonly move_learn_methods: readonly VersionGroupDetailMoveLearnMethodsItem[];
  readonly pokedexes: readonly VersionGroupDetailPokedexesItem[];
  readonly regions: readonly VersionGroupDetailRegionsItem[];
  readonly versions: readonly VersionSummary[];
}
