/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.
 *
 * ## What is this?
 *
 * This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.
 *
 * We've covered everything from Pokémon to Berry Flavors.
 *
 * ## Where do I start?
 *
 * We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.
 *
 * This API will always be publicly available and will never require any extensive setup process to consume.
 *
 * Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors**](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
 *
 * OpenAPI spec version: 2.10.0
 */
import { HttpHeaders, httpResource } from '@angular/common/http';
import type {
  HttpContext,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest,
} from '@angular/common/http';

import type { ResourceStatus, Signal } from '@angular/core';

import type {
  AbilityDetail,
  AbilityListParams,
  CharacteristicDetail,
  CharacteristicListParams,
  EggGroupDetail,
  EggGroupListParams,
  GenderDetail,
  GenderListParams,
  GrowthRateDetail,
  GrowthRateListParams,
  MoveDamageClassDetail,
  MoveDamageClassListParams,
  NatureDetail,
  NatureListParams,
  PaginatedAbilitySummaryList,
  PaginatedCharacteristicSummaryList,
  PaginatedEggGroupSummaryList,
  PaginatedGenderSummaryList,
  PaginatedGrowthRateSummaryList,
  PaginatedMoveDamageClassSummaryList,
  PaginatedNatureSummaryList,
  PaginatedPokeathlonStatSummaryList,
  PaginatedPokemonColorSummaryList,
  PaginatedPokemonFormSummaryList,
  PaginatedPokemonHabitatSummaryList,
  PaginatedPokemonShapeSummaryList,
  PaginatedPokemonSpeciesSummaryList,
  PaginatedPokemonSummaryList,
  PaginatedStatSummaryList,
  PaginatedTypeSummaryList,
  PokeathlonStatDetail,
  PokeathlonStatListParams,
  PokemonColorDetail,
  PokemonColorListParams,
  PokemonDetail,
  PokemonFormDetail,
  PokemonFormListParams,
  PokemonHabitatDetail,
  PokemonHabitatListParams,
  PokemonListParams,
  PokemonShapeDetail,
  PokemonShapeListParams,
  PokemonSpeciesDetail,
  PokemonSpeciesListParams,
  StatDetail,
  StatListParams,
  TypeDetail,
  TypeListParams,
} from '@poke/poke-api/model';

export interface OrvalHttpResourceRequestExtension {
  /** Extra headers merged over generated headers. Pass a function to read signals reactively. */
  headers?: HttpResourceRequest['headers'] | (() => HttpResourceRequest['headers']);
  /** Angular HttpContext forwarded to the underlying request. Pass a function to derive it reactively. */
  context?: HttpContext | (() => HttpContext);
  /** Last-resort escape hatch: transform the final request descriptor. Runs inside the resource's reactive context. */
  request?: (request: HttpResourceRequest) => HttpResourceRequest;
}

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = (TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>) &
  OrvalHttpResourceRequestExtension;

function mergeOrvalResourceHeaders(
  base: HttpResourceRequest['headers'],
  extra: HttpResourceRequest['headers'],
): HttpResourceRequest['headers'] {
  if (!base) return extra;
  if (!extra) return base;
  if (base instanceof HttpHeaders || extra instanceof HttpHeaders) {
    const toHeaderValue = (value: string | readonly string[]): string | string[] =>
      Array.isArray(value) ? Array.from(value, String) : String(value);
    let merged =
      base instanceof HttpHeaders
        ? base
        : Object.entries(base).reduce(
            (headers, [key, value]) => headers.set(key, toHeaderValue(value)),
            new HttpHeaders(),
          );
    const extraRecord =
      extra instanceof HttpHeaders
        ? extra.keys().reduce<Record<string, string[]>>((record, key) => {
            const values = extra.getAll(key);
            if (values) record[key] = values;
            return record;
          }, {})
        : extra;
    for (const [key, value] of Object.entries(extraRecord)) {
      merged = merged.set(key, toHeaderValue(value));
    }
    return merged;
  }
  return { ...base, ...extra };
}

export function applyOrvalRequestExtension(
  request: string | HttpResourceRequest,
  options?: OrvalHttpResourceRequestExtension,
): HttpResourceRequest {
  const base: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
  if (
    !options ||
    (options.headers === undefined &&
      options.context === undefined &&
      options.request === undefined)
  ) {
    return base;
  }
  let next: HttpResourceRequest = { ...base };
  const extraHeaders = typeof options.headers === 'function' ? options.headers() : options.headers;
  if (extraHeaders !== undefined) {
    next = { ...next, headers: mergeOrvalResourceHeaders(next.headers, extraHeaders) };
  }
  const context = typeof options.context === 'function' ? options.context() : options.context;
  if (context !== undefined) {
    next = { ...next, context };
  }
  return options.request ? options.request(next) : next;
}

type AngularHttpParamValue = string | number | boolean | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      // With a paramsSerializer (preserveRequiredNullables) the literal null
      // is passed through for it to consume; without one, emit an empty
      // string so the required key still reaches the wire as `?key=`
      // instead of being silently dropped. See #3712.
      filteredParams[key] = preserveRequiredNullables ? null : '';
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function abilityListResource(
  params: Signal<AbilityListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedAbilitySummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedAbilitySummaryList>;
  },
): HttpResourceRef<PaginatedAbilitySummaryList>;
export function abilityListResource(
  params?: Signal<AbilityListParams>,
  options?: OrvalHttpResourceOptions<PaginatedAbilitySummaryList, unknown>,
): HttpResourceRef<PaginatedAbilitySummaryList | undefined>;
export function abilityListResource(
  params?: Signal<AbilityListParams>,
  options?: OrvalHttpResourceOptions<PaginatedAbilitySummaryList, unknown>,
): HttpResourceRef<PaginatedAbilitySummaryList | undefined> {
  return httpResource<PaginatedAbilitySummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/ability/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function abilityRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<AbilityDetail, unknown> & {
    defaultValue: NoInfer<AbilityDetail>;
  },
): HttpResourceRef<AbilityDetail>;
export function abilityRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<AbilityDetail, unknown>,
): HttpResourceRef<AbilityDetail | undefined>;
export function abilityRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<AbilityDetail, unknown>,
): HttpResourceRef<AbilityDetail | undefined> {
  return httpResource<AbilityDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/ability/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function characteristicListResource(
  params: Signal<CharacteristicListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedCharacteristicSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedCharacteristicSummaryList>;
  },
): HttpResourceRef<PaginatedCharacteristicSummaryList>;
export function characteristicListResource(
  params?: Signal<CharacteristicListParams>,
  options?: OrvalHttpResourceOptions<PaginatedCharacteristicSummaryList, unknown>,
): HttpResourceRef<PaginatedCharacteristicSummaryList | undefined>;
export function characteristicListResource(
  params?: Signal<CharacteristicListParams>,
  options?: OrvalHttpResourceOptions<PaginatedCharacteristicSummaryList, unknown>,
): HttpResourceRef<PaginatedCharacteristicSummaryList | undefined> {
  return httpResource<PaginatedCharacteristicSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/characteristic/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function characteristicRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<CharacteristicDetail, unknown> & {
    defaultValue: NoInfer<CharacteristicDetail>;
  },
): HttpResourceRef<CharacteristicDetail>;
export function characteristicRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<CharacteristicDetail, unknown>,
): HttpResourceRef<CharacteristicDetail | undefined>;
export function characteristicRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<CharacteristicDetail, unknown>,
): HttpResourceRef<CharacteristicDetail | undefined> {
  return httpResource<CharacteristicDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/characteristic/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function eggGroupListResource(
  params: Signal<EggGroupListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedEggGroupSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedEggGroupSummaryList>;
  },
): HttpResourceRef<PaginatedEggGroupSummaryList>;
export function eggGroupListResource(
  params?: Signal<EggGroupListParams>,
  options?: OrvalHttpResourceOptions<PaginatedEggGroupSummaryList, unknown>,
): HttpResourceRef<PaginatedEggGroupSummaryList | undefined>;
export function eggGroupListResource(
  params?: Signal<EggGroupListParams>,
  options?: OrvalHttpResourceOptions<PaginatedEggGroupSummaryList, unknown>,
): HttpResourceRef<PaginatedEggGroupSummaryList | undefined> {
  return httpResource<PaginatedEggGroupSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/egg-group/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function eggGroupRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<EggGroupDetail, unknown> & {
    defaultValue: NoInfer<EggGroupDetail>;
  },
): HttpResourceRef<EggGroupDetail>;
export function eggGroupRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<EggGroupDetail, unknown>,
): HttpResourceRef<EggGroupDetail | undefined>;
export function eggGroupRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<EggGroupDetail, unknown>,
): HttpResourceRef<EggGroupDetail | undefined> {
  return httpResource<EggGroupDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/egg-group/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function genderListResource(
  params: Signal<GenderListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedGenderSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedGenderSummaryList>;
  },
): HttpResourceRef<PaginatedGenderSummaryList>;
export function genderListResource(
  params?: Signal<GenderListParams>,
  options?: OrvalHttpResourceOptions<PaginatedGenderSummaryList, unknown>,
): HttpResourceRef<PaginatedGenderSummaryList | undefined>;
export function genderListResource(
  params?: Signal<GenderListParams>,
  options?: OrvalHttpResourceOptions<PaginatedGenderSummaryList, unknown>,
): HttpResourceRef<PaginatedGenderSummaryList | undefined> {
  return httpResource<PaginatedGenderSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/gender/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function genderRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<GenderDetail, unknown> & {
    defaultValue: NoInfer<GenderDetail>;
  },
): HttpResourceRef<GenderDetail>;
export function genderRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<GenderDetail, unknown>,
): HttpResourceRef<GenderDetail | undefined>;
export function genderRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<GenderDetail, unknown>,
): HttpResourceRef<GenderDetail | undefined> {
  return httpResource<GenderDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/gender/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function growthRateListResource(
  params: Signal<GrowthRateListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedGrowthRateSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedGrowthRateSummaryList>;
  },
): HttpResourceRef<PaginatedGrowthRateSummaryList>;
export function growthRateListResource(
  params?: Signal<GrowthRateListParams>,
  options?: OrvalHttpResourceOptions<PaginatedGrowthRateSummaryList, unknown>,
): HttpResourceRef<PaginatedGrowthRateSummaryList | undefined>;
export function growthRateListResource(
  params?: Signal<GrowthRateListParams>,
  options?: OrvalHttpResourceOptions<PaginatedGrowthRateSummaryList, unknown>,
): HttpResourceRef<PaginatedGrowthRateSummaryList | undefined> {
  return httpResource<PaginatedGrowthRateSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/growth-rate/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function growthRateRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<GrowthRateDetail, unknown> & {
    defaultValue: NoInfer<GrowthRateDetail>;
  },
): HttpResourceRef<GrowthRateDetail>;
export function growthRateRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<GrowthRateDetail, unknown>,
): HttpResourceRef<GrowthRateDetail | undefined>;
export function growthRateRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<GrowthRateDetail, unknown>,
): HttpResourceRef<GrowthRateDetail | undefined> {
  return httpResource<GrowthRateDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/growth-rate/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveDamageClassListResource(
  params: Signal<MoveDamageClassListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedMoveDamageClassSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedMoveDamageClassSummaryList>;
  },
): HttpResourceRef<PaginatedMoveDamageClassSummaryList>;
export function moveDamageClassListResource(
  params?: Signal<MoveDamageClassListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveDamageClassSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveDamageClassSummaryList | undefined>;
export function moveDamageClassListResource(
  params?: Signal<MoveDamageClassListParams>,
  options?: OrvalHttpResourceOptions<PaginatedMoveDamageClassSummaryList, unknown>,
): HttpResourceRef<PaginatedMoveDamageClassSummaryList | undefined> {
  return httpResource<PaginatedMoveDamageClassSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/move-damage-class/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function moveDamageClassRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<MoveDamageClassDetail, unknown> & {
    defaultValue: NoInfer<MoveDamageClassDetail>;
  },
): HttpResourceRef<MoveDamageClassDetail>;
export function moveDamageClassRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveDamageClassDetail, unknown>,
): HttpResourceRef<MoveDamageClassDetail | undefined>;
export function moveDamageClassRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<MoveDamageClassDetail, unknown>,
): HttpResourceRef<MoveDamageClassDetail | undefined> {
  return httpResource<MoveDamageClassDetail>(
    () =>
      applyOrvalRequestExtension(`https://pokeapi.co/api/v2/move-damage-class/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function natureListResource(
  params: Signal<NatureListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedNatureSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedNatureSummaryList>;
  },
): HttpResourceRef<PaginatedNatureSummaryList>;
export function natureListResource(
  params?: Signal<NatureListParams>,
  options?: OrvalHttpResourceOptions<PaginatedNatureSummaryList, unknown>,
): HttpResourceRef<PaginatedNatureSummaryList | undefined>;
export function natureListResource(
  params?: Signal<NatureListParams>,
  options?: OrvalHttpResourceOptions<PaginatedNatureSummaryList, unknown>,
): HttpResourceRef<PaginatedNatureSummaryList | undefined> {
  return httpResource<PaginatedNatureSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/nature/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function natureRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<NatureDetail, unknown> & {
    defaultValue: NoInfer<NatureDetail>;
  },
): HttpResourceRef<NatureDetail>;
export function natureRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<NatureDetail, unknown>,
): HttpResourceRef<NatureDetail | undefined>;
export function natureRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<NatureDetail, unknown>,
): HttpResourceRef<NatureDetail | undefined> {
  return httpResource<NatureDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/nature/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonListResource(
  params: Signal<PokemonListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPokemonSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPokemonSummaryList>;
  },
): HttpResourceRef<PaginatedPokemonSummaryList>;
export function pokemonListResource(
  params?: Signal<PokemonListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonSummaryList | undefined>;
export function pokemonListResource(
  params?: Signal<PokemonListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonSummaryList | undefined> {
  return httpResource<PaginatedPokemonSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pokemon/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PokemonDetail, unknown> & {
    defaultValue: NoInfer<PokemonDetail>;
  },
): HttpResourceRef<PokemonDetail>;
export function pokemonRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonDetail, unknown>,
): HttpResourceRef<PokemonDetail | undefined>;
export function pokemonRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonDetail, unknown>,
): HttpResourceRef<PokemonDetail | undefined> {
  return httpResource<PokemonDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pokemon/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonColorListResource(
  params: Signal<PokemonColorListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPokemonColorSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPokemonColorSummaryList>;
  },
): HttpResourceRef<PaginatedPokemonColorSummaryList>;
export function pokemonColorListResource(
  params?: Signal<PokemonColorListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonColorSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonColorSummaryList | undefined>;
export function pokemonColorListResource(
  params?: Signal<PokemonColorListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonColorSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonColorSummaryList | undefined> {
  return httpResource<PaginatedPokemonColorSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pokemon-color/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonColorRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PokemonColorDetail, unknown> & {
    defaultValue: NoInfer<PokemonColorDetail>;
  },
): HttpResourceRef<PokemonColorDetail>;
export function pokemonColorRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonColorDetail, unknown>,
): HttpResourceRef<PokemonColorDetail | undefined>;
export function pokemonColorRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonColorDetail, unknown>,
): HttpResourceRef<PokemonColorDetail | undefined> {
  return httpResource<PokemonColorDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pokemon-color/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonFormListResource(
  params: Signal<PokemonFormListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPokemonFormSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPokemonFormSummaryList>;
  },
): HttpResourceRef<PaginatedPokemonFormSummaryList>;
export function pokemonFormListResource(
  params?: Signal<PokemonFormListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonFormSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonFormSummaryList | undefined>;
export function pokemonFormListResource(
  params?: Signal<PokemonFormListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonFormSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonFormSummaryList | undefined> {
  return httpResource<PaginatedPokemonFormSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pokemon-form/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonFormRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PokemonFormDetail, unknown> & {
    defaultValue: NoInfer<PokemonFormDetail>;
  },
): HttpResourceRef<PokemonFormDetail>;
export function pokemonFormRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonFormDetail, unknown>,
): HttpResourceRef<PokemonFormDetail | undefined>;
export function pokemonFormRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonFormDetail, unknown>,
): HttpResourceRef<PokemonFormDetail | undefined> {
  return httpResource<PokemonFormDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pokemon-form/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonHabitatListResource(
  params: Signal<PokemonHabitatListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPokemonHabitatSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPokemonHabitatSummaryList>;
  },
): HttpResourceRef<PaginatedPokemonHabitatSummaryList>;
export function pokemonHabitatListResource(
  params?: Signal<PokemonHabitatListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonHabitatSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonHabitatSummaryList | undefined>;
export function pokemonHabitatListResource(
  params?: Signal<PokemonHabitatListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonHabitatSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonHabitatSummaryList | undefined> {
  return httpResource<PaginatedPokemonHabitatSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pokemon-habitat/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonHabitatRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PokemonHabitatDetail, unknown> & {
    defaultValue: NoInfer<PokemonHabitatDetail>;
  },
): HttpResourceRef<PokemonHabitatDetail>;
export function pokemonHabitatRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonHabitatDetail, unknown>,
): HttpResourceRef<PokemonHabitatDetail | undefined>;
export function pokemonHabitatRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonHabitatDetail, unknown>,
): HttpResourceRef<PokemonHabitatDetail | undefined> {
  return httpResource<PokemonHabitatDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pokemon-habitat/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonShapeListResource(
  params: Signal<PokemonShapeListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPokemonShapeSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPokemonShapeSummaryList>;
  },
): HttpResourceRef<PaginatedPokemonShapeSummaryList>;
export function pokemonShapeListResource(
  params?: Signal<PokemonShapeListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonShapeSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonShapeSummaryList | undefined>;
export function pokemonShapeListResource(
  params?: Signal<PokemonShapeListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonShapeSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonShapeSummaryList | undefined> {
  return httpResource<PaginatedPokemonShapeSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pokemon-shape/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonShapeRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PokemonShapeDetail, unknown> & {
    defaultValue: NoInfer<PokemonShapeDetail>;
  },
): HttpResourceRef<PokemonShapeDetail>;
export function pokemonShapeRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonShapeDetail, unknown>,
): HttpResourceRef<PokemonShapeDetail | undefined>;
export function pokemonShapeRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonShapeDetail, unknown>,
): HttpResourceRef<PokemonShapeDetail | undefined> {
  return httpResource<PokemonShapeDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pokemon-shape/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonSpeciesListResource(
  params: Signal<PokemonSpeciesListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPokemonSpeciesSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPokemonSpeciesSummaryList>;
  },
): HttpResourceRef<PaginatedPokemonSpeciesSummaryList>;
export function pokemonSpeciesListResource(
  params?: Signal<PokemonSpeciesListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonSpeciesSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonSpeciesSummaryList | undefined>;
export function pokemonSpeciesListResource(
  params?: Signal<PokemonSpeciesListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokemonSpeciesSummaryList, unknown>,
): HttpResourceRef<PaginatedPokemonSpeciesSummaryList | undefined> {
  return httpResource<PaginatedPokemonSpeciesSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pokemon-species/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokemonSpeciesRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PokemonSpeciesDetail, unknown> & {
    defaultValue: NoInfer<PokemonSpeciesDetail>;
  },
): HttpResourceRef<PokemonSpeciesDetail>;
export function pokemonSpeciesRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonSpeciesDetail, unknown>,
): HttpResourceRef<PokemonSpeciesDetail | undefined>;
export function pokemonSpeciesRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokemonSpeciesDetail, unknown>,
): HttpResourceRef<PokemonSpeciesDetail | undefined> {
  return httpResource<PokemonSpeciesDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pokemon-species/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokeathlonStatListResource(
  params: Signal<PokeathlonStatListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedPokeathlonStatSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedPokeathlonStatSummaryList>;
  },
): HttpResourceRef<PaginatedPokeathlonStatSummaryList>;
export function pokeathlonStatListResource(
  params?: Signal<PokeathlonStatListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokeathlonStatSummaryList, unknown>,
): HttpResourceRef<PaginatedPokeathlonStatSummaryList | undefined>;
export function pokeathlonStatListResource(
  params?: Signal<PokeathlonStatListParams>,
  options?: OrvalHttpResourceOptions<PaginatedPokeathlonStatSummaryList, unknown>,
): HttpResourceRef<PaginatedPokeathlonStatSummaryList | undefined> {
  return httpResource<PaginatedPokeathlonStatSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/pokeathlon-stat/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function pokeathlonStatRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<PokeathlonStatDetail, unknown> & {
    defaultValue: NoInfer<PokeathlonStatDetail>;
  },
): HttpResourceRef<PokeathlonStatDetail>;
export function pokeathlonStatRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokeathlonStatDetail, unknown>,
): HttpResourceRef<PokeathlonStatDetail | undefined>;
export function pokeathlonStatRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<PokeathlonStatDetail, unknown>,
): HttpResourceRef<PokeathlonStatDetail | undefined> {
  return httpResource<PokeathlonStatDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/pokeathlon-stat/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function statListResource(
  params: Signal<StatListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedStatSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedStatSummaryList>;
  },
): HttpResourceRef<PaginatedStatSummaryList>;
export function statListResource(
  params?: Signal<StatListParams>,
  options?: OrvalHttpResourceOptions<PaginatedStatSummaryList, unknown>,
): HttpResourceRef<PaginatedStatSummaryList | undefined>;
export function statListResource(
  params?: Signal<StatListParams>,
  options?: OrvalHttpResourceOptions<PaginatedStatSummaryList, unknown>,
): HttpResourceRef<PaginatedStatSummaryList | undefined> {
  return httpResource<PaginatedStatSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/stat/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function statRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<StatDetail, unknown> & { defaultValue: NoInfer<StatDetail> },
): HttpResourceRef<StatDetail>;
export function statRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<StatDetail, unknown>,
): HttpResourceRef<StatDetail | undefined>;
export function statRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<StatDetail, unknown>,
): HttpResourceRef<StatDetail | undefined> {
  return httpResource<StatDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/stat/${id()}/`, options),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function typeListResource(
  params: Signal<TypeListParams> | undefined,
  options: OrvalHttpResourceOptions<PaginatedTypeSummaryList, unknown> & {
    defaultValue: NoInfer<PaginatedTypeSummaryList>;
  },
): HttpResourceRef<PaginatedTypeSummaryList>;
export function typeListResource(
  params?: Signal<TypeListParams>,
  options?: OrvalHttpResourceOptions<PaginatedTypeSummaryList, unknown>,
): HttpResourceRef<PaginatedTypeSummaryList | undefined>;
export function typeListResource(
  params?: Signal<TypeListParams>,
  options?: OrvalHttpResourceOptions<PaginatedTypeSummaryList, unknown>,
): HttpResourceRef<PaginatedTypeSummaryList | undefined> {
  return httpResource<PaginatedTypeSummaryList>(() => {
    const request = {
      url: `https://pokeapi.co/api/v2/type/`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    return applyOrvalRequestExtension(request, options);
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function typeRetrieveResource(
  id: Signal<string>,
  options: OrvalHttpResourceOptions<TypeDetail, unknown> & { defaultValue: NoInfer<TypeDetail> },
): HttpResourceRef<TypeDetail>;
export function typeRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<TypeDetail, unknown>,
): HttpResourceRef<TypeDetail | undefined>;
export function typeRetrieveResource(
  id: Signal<string>,
  options?: OrvalHttpResourceOptions<TypeDetail, unknown>,
): HttpResourceRef<TypeDetail | undefined> {
  return httpResource<TypeDetail>(
    () => applyOrvalRequestExtension(`https://pokeapi.co/api/v2/type/${id()}/`, options),
    options,
  );
}

export type AbilityListResourceResult = NonNullable<PaginatedAbilitySummaryList>;
export type AbilityRetrieveResourceResult = NonNullable<AbilityDetail>;
export type CharacteristicListResourceResult = NonNullable<PaginatedCharacteristicSummaryList>;
export type CharacteristicRetrieveResourceResult = NonNullable<CharacteristicDetail>;
export type EggGroupListResourceResult = NonNullable<PaginatedEggGroupSummaryList>;
export type EggGroupRetrieveResourceResult = NonNullable<EggGroupDetail>;
export type GenderListResourceResult = NonNullable<PaginatedGenderSummaryList>;
export type GenderRetrieveResourceResult = NonNullable<GenderDetail>;
export type GrowthRateListResourceResult = NonNullable<PaginatedGrowthRateSummaryList>;
export type GrowthRateRetrieveResourceResult = NonNullable<GrowthRateDetail>;
export type MoveDamageClassListResourceResult = NonNullable<PaginatedMoveDamageClassSummaryList>;
export type MoveDamageClassRetrieveResourceResult = NonNullable<MoveDamageClassDetail>;
export type NatureListResourceResult = NonNullable<PaginatedNatureSummaryList>;
export type NatureRetrieveResourceResult = NonNullable<NatureDetail>;
export type PokemonListResourceResult = NonNullable<PaginatedPokemonSummaryList>;
export type PokemonRetrieveResourceResult = NonNullable<PokemonDetail>;
export type PokemonColorListResourceResult = NonNullable<PaginatedPokemonColorSummaryList>;
export type PokemonColorRetrieveResourceResult = NonNullable<PokemonColorDetail>;
export type PokemonFormListResourceResult = NonNullable<PaginatedPokemonFormSummaryList>;
export type PokemonFormRetrieveResourceResult = NonNullable<PokemonFormDetail>;
export type PokemonHabitatListResourceResult = NonNullable<PaginatedPokemonHabitatSummaryList>;
export type PokemonHabitatRetrieveResourceResult = NonNullable<PokemonHabitatDetail>;
export type PokemonShapeListResourceResult = NonNullable<PaginatedPokemonShapeSummaryList>;
export type PokemonShapeRetrieveResourceResult = NonNullable<PokemonShapeDetail>;
export type PokemonSpeciesListResourceResult = NonNullable<PaginatedPokemonSpeciesSummaryList>;
export type PokemonSpeciesRetrieveResourceResult = NonNullable<PokemonSpeciesDetail>;
export type PokeathlonStatListResourceResult = NonNullable<PaginatedPokeathlonStatSummaryList>;
export type PokeathlonStatRetrieveResourceResult = NonNullable<PokeathlonStatDetail>;
export type StatListResourceResult = NonNullable<PaginatedStatSummaryList>;
export type StatRetrieveResourceResult = NonNullable<StatDetail>;
export type TypeListResourceResult = NonNullable<PaginatedTypeSummaryList>;
export type TypeRetrieveResourceResult = NonNullable<TypeDetail>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
