import { computed, signal, Service } from '@angular/core';
import type { EvoStep } from '@poke/poke-data';

/** One creature in the catalog (subset of PokeDetail + evolution info). */
export interface CatalogCreature {
  id: number;
  name: string;
  types: string[];
  stats: {
    hp: number;
    attack: number;
    defense: number;
    spAtk: number;
    spDef: number;
    speed: number;
  };
  baseExperience: number;
  spriteUrl: string;
  artworkUrl: string;
  moves: { name: string; level: number }[];
  abilities: { name: string; isHidden: boolean }[];
  flavor: string | null;
  evolvesFrom: string | null;
  evolvesTo: { species: string; trigger: string }[];
}

interface CatalogData {
  app: string;
  version: number;
  maxGen: number;
  creatures: Record<string, CatalogCreature>;
  moves: Record<
    string,
    { name: string; type: string; category: 'physical' | 'special'; power: number }
  >;
  abilities: Record<string, string>;
  zones: Record<string, { name: string; encounters: string[] }>;
}

/**
 * Local snapshot of everything the game consumes from PokeAPI
 * (`public/catalog.json`, generated by `tools/export-catalog.mjs`). Loaded
 * once at boot in the background; when ready it SEEDS the same in-memory
 * caches PokeData uses, so the network resources short-circuit and the app
 * works fully offline. The catalog shape is the contract a future backend
 * must serve — see docs/backend-catalog.md.
 */
@Service()
export class LocalCatalog {
  #_loaded = signal(false);
  readonly loaded = this.#_loaded.asReadonly();
  readonly loading = signal(false);

  #creatures = new Map<string, CatalogCreature>();
  #moves = new Map<
    string,
    { name: string; type: string; category: 'physical' | 'special'; power: number }
  >();
  #abilities = new Map<string, string>();
  #zones = new Map<string, { name: string; encounters: string[] }>();

  /** Raw maps (used by PokeData to seed its caches). */
  readonly movesMap = this.#moves;
  readonly abilitiesMap = this.#abilities;
  readonly zonesMap = this.#zones;
  /** species → flat evolution steps (reconstructed from evolvesTo/evolvesFrom). */
  #chains = new Map<string, EvoStep[]>();
  /** species → its evolution chain id (drives apex detection). */
  #chainIds = new Map<string, string>();

  /** All creatures sorted by dex id (drives the master list when loaded). */
  readonly creatures = computed<CatalogCreature[]>(() =>
    [...this.#creatures.values()].sort((a, b) => a.id - b.id),
  );

  /** Fetch + parse the catalog once (idempotent). */
  async load(): Promise<void> {
    if (this.#_loaded() || this.loading()) return;
    this.loading.set(true);
    try {
      const res = await fetch('catalog.json');
      if (!res.ok) throw new Error(`catalog fetch ${res.status}`);
      const data = (await res.json()) as CatalogData;
      for (const [name, c] of Object.entries(data.creatures ?? {})) this.#creatures.set(name, c);
      for (const [name, m] of Object.entries(data.moves ?? {})) this.#moves.set(name, m);
      for (const [name, a] of Object.entries(data.abilities ?? {})) this.#abilities.set(name, a);
      for (const [url, z] of Object.entries(data.zones ?? {})) this.#zones.set(url, z);
      this.rebuildChains();
      this.#_loaded.set(true);
    } catch {
      // No catalog (dev without the file) — the app keeps using PokeAPI.
    } finally {
      this.loading.set(false);
    }
  }

  /** Reconstruct each species' flat evolution chain from evolvesTo/evolvesFrom. */
  private rebuildChains() {
    const root = (name: string): string => {
      const from = this.#creatures.get(name)?.evolvesFrom;
      return from ? root(from) : name;
    };
    const chainOf = (start: string): EvoStep[] => {
      const edges: EvoStep[] = [];
      const seen = new Set<string>();
      const walk = (n: string) => {
        if (seen.has(n)) return;
        seen.add(n);
        const next = this.#creatures.get(n)?.evolvesTo ?? [];
        for (const e of next) {
          edges.push({ species: n, to: e.species, trigger: e.trigger });
          walk(e.species);
        }
      };
      walk(start);
      return edges;
    };
    for (const name of this.#creatures.keys()) {
      const r = root(name);
      this.#chains.set(name, chainOf(r));
      this.#chainIds.set(name, String(this.#creatures.get(r)?.id ?? 0));
    }
  }

  // --- getters (mirror PokeData's cache accessors) ---

  creature(name: string): CatalogCreature | null {
    return this.#creatures.get(name.toLowerCase()) ?? null;
  }

  move(
    name: string,
  ): { name: string; type: string; category: 'physical' | 'special'; power: number } | null {
    return this.#moves.get(name) ?? null;
  }

  abilityEffect(name: string): string | null {
    return this.#abilities.get(name) ?? null;
  }

  flavor(name: string): string | null {
    return this.#creatures.get(name.toLowerCase())?.flavor ?? null;
  }

  evolvesFrom(name: string): string | null | undefined {
    const c = this.#creatures.get(name.toLowerCase());
    return c ? c.evolvesFrom : undefined;
  }

  flatChain(name: string): EvoStep[] {
    return this.#chains.get(name.toLowerCase()) ?? [];
  }

  hasChain(name: string): boolean {
    return this.#chainIds.has(name.toLowerCase());
  }

  zone(url: string): { name: string; encounters: string[] } | null {
    return this.#zones.get(url) ?? null;
  }

  isLoaded(): boolean {
    return this.#_loaded();
  }
}
